config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :cartes

  root to: 'cartes#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/carte.rb
class Carte < ApplicationRecord

  validates :title,    presence: true
  validates :subtitle, presence: true
  validates :position, presence: true, numericality: true

  scope :by_position, ->(){ order(:position) }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  

end

app/controllers/cartes_controller.rb
class CartesController < ApplicationController

  def index
    @cartes = Carte.by_position
  end

  def new
    @carte = Carte.new
  end

  def create
    @carte = Carte.new( carte_params )
    if @carte.save
      redirect_to action: :index
    else
      render action: :new
    end
  end

  def edit
    @carte = Carte.find(params[:id])
  end

  def update
    @carte = Carte.find(params[:id])
    if @carte.update_attributes carte_params
      redirect_to action: :index
    else
      render action: :edit
    end
  end

  def destroy
    @carte = Carte.find(params[:id])
    @carte.destroy
    redirect_to action: :index
  end

  def carte_params
    params.require(:carte).permit(:title, :subtitle, :position)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper


end

app/helpers/cartes_helper.rb
module CartesHelper
end

app/views/cartes/_carte.html.haml
%div
  %div
    =link_to(carte.title, edit_carte_url(carte))
  %div
    =carte.subtitle
  %div
    =carte.position
  %div
    =button_to "x", carte_url(carte),  method: :delete

app/views/cartes/edit.html.haml
%h2
  Edit Menu Form

%div
  =@carte.errors.full_messages.join(' - ')

=form_for(@carte) do |f|
  %div
    = f.label :title
    = f.text_field :title

  %div
    = f.label :subtitle
    = f.text_field :subtitle

  %div
    = f.label :position
    = f.text_field :position

  %div
    = f.submit "Update"

 

app/views/cartes/index.html.haml
= link_to("Add Menu", new_carte_url)

%div
  -if @cartes.empty?
    No cartes yet
  -else
    %h4
      Cartes
    =render partial: 'carte', collection: @cartes

app/views/cartes/new.html.haml
%h2
  New Menu Form

=form_for(@carte) do |f|
  = f.label :title
  = f.text_field :title

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Menu</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>